Release version 2.2.0
GitOrigin-RevId: 7915ce6851f9160ab3c850c7e8b2447f78d8e9d2

diff --git a/scripts/entrypoint_docker b/scripts/entrypoint_docker
--- a/scripts/entrypoint_docker
+++ b/scripts/entrypoint_docker
@@ -48,7 +48,13 @@ fi
 
 {
 if ! getent group "${GROUP}" > /dev/null 2>&1; then
-  groupadd -g "${GROUP_ID}" "${GROUP}"
+    if getent group "${GROUP_ID}" > /dev/null 2>&1; then
+        # GID is in use by another group
+        echo "Cannot create group **${GROUP}**. GID **${GROUP_ID}** is already in use. Skipping groupadd." >&2
+    else
+        echo "Adding new group **${GROUP}** with GID **${GROUP_ID}**." >&2
+        groupadd -g "${GROUP_ID}" "${GROUP}"
+    fi
 fi
 
 if ! id -u "${USER}" > /dev/null 2>&1; then
